version: '3.4'

services:
  deltaTre.search.presentation.rpc:
    image: ${DOCKER_REGISTRY-}deltatre.grpc
    hostname: deltaTre.search.presentation.rpc
    build:
      context: ./backend
      dockerfile: DeltaTre.Search.Presentation.Rpc/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     

  deltaTre.presentation.api:
    image: ${DOCKER_REGISTRY-}deltatre.api
    hostname: deltaTre.presentation.api
    build:
      context: ./frontend
      dockerfile: DeltaTre.Presentation.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcConfig__Server=http://deltaTre.search.presentation.rpc
    depends_on:
      - deltaTre.search.presentation.rpc
